import { ICardConfig } from "./types"

export const defaults: ICardConfig = {
  NEW_STEPS_MINUTES: [1, 10],
  GRADUATING_INTERVAL_DAYS: 1,
  INTERVAL_MODIFIER_PERCENT: 192,
  MAXIMUM_INTERVAL_DAYS: 36500,
  LAPSES_STEPS_MINUTES: [10],
  NEW_INTERVAL_PERCENT: 50,
  MINIMUM_INTERVAL_DAYS: 1,
}
