export interface ICardConfig {
  NEW_STEPS_MINUTES: number[]
  GRADUATING_INTERVAL_DAYS: number
  INTERVAL_MODIFIER_PERCENT: number
  MAXIMUM_INTERVAL_DAYS: number
  LAPSES_STEPS_MINUTES: number[]
  NEW_INTERVAL_PERCENT: number
  MINIMUM_INTERVAL_DAYS: number
}
